#!/bin/bash

## This shell script was integrated into the single python script channel_changer.py

## This script is used to set a random wallpaper from a directory. 
## The shuf command is used to randomly select a file from the specified directory. 
## The wallpaper is then set using the pcmanfm command. 
## The script exits with a status of 0.

# Store directory of wallpapers in variable 
wp_directory="/home/pi/Desktop/backgrounds/*"

# Select a random wallpaper from the directory 
random_file=$(shuf -n1 -e $wp_directory)

# Set the wallpaper using pcmanfm 
pcmanfm --set-wallpaper="$random_file" 
exit 0

# https://forums.raspberrypi.com/viewtopic.php?t=51744 Wallz - A new lightweight wallpaper slide show
# http://stackoverflow.com/questions/701505/best-way-to-choose-a-random-file-from-a-directory-in-a-shell-script
# https://www.mankier.com/1/pcmanfm
#
## https://tvtanks.com
## https://github.com/martinvicknair
